version: "2"

services:
  voting-app:
    labels:
      - "interlock.hostname=votingApp"
      - "interlock.domain=git2swarm.com"

  result-app:
    labels:
      - "interlock.hostname=results"
      - "interlock.domain=git2swarm.com"

