version: "2"

services:
  interlock:
    image: ehazlett/interlock:1.0.1
    command: -D run
    container_name: interlock
    tty: true
    ports:
        - 8080
    environment:
        INTERLOCK_CONFIG: |
            ListenAddr = ":8080"
            DockerURL = "${DOCKER_HOST}"

            [[Extensions]]
            Name = "nginx"
            ConfigPath = "/etc/conf/nginx.conf"
            PidPath = "/etc/conf/nginx.pid"
            MaxConn = 1024
            Port = 80
    volumes:
        - nginx:/etc/conf
        #- /var/tmp/config.toml:/bin/config.toml

  nginx:
    image: nginx:latest
    entrypoint: nginx
    command: -g "daemon off;" -c /etc/conf/nginx.conf
    ports:
        - 80:80
    environment:
        - "constraint:node==ip-172-31-1-154"
    labels:
        - "interlock.ext.name=nginx"
    volumes:
        - nginx:/etc/conf

volumes:
  nginx:
    driver: local
